name: 'Export Salesforce Changeset'
description: 'Copies the contents of a Salesforce Changeset.'
inputs:
  serverKey:
    description: 'Connected App Digital Certificate'
    required: true
  clientId:
    description: 'Connected App Client Id'
    required: true
  username:
    description: 'Salesforce Username'
    required: true
  changesetName:
    description: 'Package or Changeset Name'
    required: true
    default: 'MoveDataDev'
  folder:
    description: 'File to export the data'
    required: true
    default: './'
outputs:
  folder:
    description: 'File where the data has been exported'
runs:
  using: 'node16'
  main: 'index.js'