name: 'Export Salesforce Changeset'
description: 'Copies the contents of a Salesforce Changeset.'
inputs:
  serverKey:
    description: 'Connected App Digital Certificate'
    required: true
  clientId:
    description: 'Connected App Client Id'
    required: true
  username:
    description: 'Salesforce Username'
    required: true
  folder:
    description: 'File to export the data'
    required: true
    default: './'
outputs:
  folder:
    description: 'File where the data has been exported'
runs:
  - name: Setup Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '16'
  - name: Cache dependencies
    uses: actions/cache@v2
    with:
      path: ~/.npm
      key: npm-${{ hashFiles('package-lock.json') }}
      restore-keys: npm-
  using: 'node16'
  main: 'index.js'